[package]
name = "futurecommander"
version = "0.3.5"
authors = ["Fran√ßois Cadeillan <francois@azsystem.fr>"]
edition = "2018"
license = "GPL-3.0-or-later"

[workspace]

[dependencies]
futurecommander_shell = { version = "0.3.5", path = "src/shell" }

